spring.datasource.url=jdbc:postgresql://localhost:5472/eventhive_db
spring.datasource.username=postgres
spring.datasource.password=Imal2023Imasha


spring.jpa.show-sql=true
# Groq API Configuration

# Hugging Face API Configuration
huggingface.api.key=hf_GmRQRSrQDTdajPgeACHjzuMCCjElDdWkHehf_GmRQRSrQDTdajPgeACHjzuMCCjElDdWkHe
spring.jpa.hibernate.ddl-auto=update

# Email Settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gamagepawani40@gmail.com

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# PayHere Payment Gateway Details
payhere.merchant.id=1237641
spring.config.import=optional:classpath:secret.properties  
 
